# Docker Compose untuk Development & Testing
version: '3.8'

services:
  # Database Service
  postgres:
    image: postgres:15-alpine
    container_name: restaurant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_pass
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant_user -d restaurant_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application Service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      # Override for docker-compose development
      DATABASE_URL: postgresql://restaurant_user:restaurant_pass@postgres:5432/restaurant_db
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data: